services:
  cricket_analytics:
    image: postgres:16-alpine
    container_name: cricket_analytics
    restart: unless-stopped
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: cricket_analytics
      POSTGRES_USER: cricket_user
      POSTGRES_PASSWORD: cricket_pass
    volumes:
      - cricket_analytics_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cricket_user -d cricket_analytics"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  cricket_analytics_data:
